#!/usr/bin/env python3
"""Write the mission set into the Obsidian plan note, from the config.

    python tools/sync_missions_to_vault.py            # update the note
    python tools/sync_missions_to_vault.py --check    # report drift, change nothing

WHY THIS EXISTS
---------------
The vault and the repository answer different questions. `AUV-02` section 1.3
says the baseline needs "ten missions spanning" eight categories; it never names
them. The concrete set lives here, in configs/missions/baseline_v1.toml.

That split is right -- the plan sets requirements, the repository implements
them -- but it meant someone reading only the plan could not tell what M05
actually is, which caused exactly that confusion on 2026-09-28.

So the plan note now carries the missions too, generated rather than copied. A
hand-copied table would drift the first time a mission changed, and a stale
mission table in the *plan* is worse than none: it is the document people trust
to say what the experiment is.

The generated block sits between HTML comment markers and nothing outside them
is touched, so the note stays hand-editable everywhere else.
"""

from __future__ import annotations

import argparse
import io
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_CONFIG = os.path.join(REPO, "configs", "missions", "baseline_v1.toml")
DEFAULT_NOTE = (
    r"D:/Product Files/Obsidian Vault/Second Brain/Second Brain/Year 2026"
    r"/Agentic UAV Research/00 Foundations — Phases 0-1/AUV-02 — Baseline Freeze.md"
)

START = "<!-- missions:start -- generated by tools/sync_missions_to_vault.py -->"
END = "<!-- missions:end -->"


def load_toml(path: str) -> dict:
    """tomllib on 3.11+, tomli on 3.10. Binary mode: both parsers require it."""
    try:
        import tomllib as reader
    except ModuleNotFoundError:
        import tomli as reader
    with open(path, "rb") as handle:
        return reader.load(handle)


def render(config: dict) -> str:
    """Build the Markdown block that goes into the note."""
    meta = config["set"]
    protocol = config["protocol"]
    missions = config["mission"]

    single = [m for m in missions if m.get("drones", 1) == 1]
    multi = [m for m in missions if m.get("drones", 1) > 1]

    lines = [
        START,
        "",
        f"### The ten missions — `{meta['name']}` v{meta['version']}",
        "",
        "Generated from `configs/missions/baseline_v1.toml` in the repository, "
        "which is the source of truth. Do not edit this block by hand; re-run "
        "`tools/sync_missions_to_vault.py` instead.",
        "",
        f"**Protocol.** `{protocol['model']}` primary, {protocol['repeats']} runs "
        f"per mission, {protocol['map']}, traffic "
        f"{'on' if protocol.get('traffic') else 'off'}, "
        f"temperature {protocol['options']['temperature']}, "
        f"`num_gpu {protocol['options']['num_gpu']}` (the GPU belongs to the simulator).",
        "",
        "> [!warning] Do not edit an instruction after results are recorded",
        "> A changed instruction under an unchanged id silently invalidates every "
        "comparison that cites it. Add `M11`; leave `M05` alone.",
        "",
        "#### Single drone",
        "",
        "| ID | Category | Instruction | Expected sequence |",
        "|---|---|---|---|",
    ]

    for mission in single:
        expected = (
            " → ".join(f"`{a}`" for a in mission["expected"])
            if mission.get("scoreable", True) and mission.get("expected")
            else "*unscoreable — no single correct answer*"
        )
        lines.append(
            f"| **{mission['id']}** | {mission.get('category', '')} "
            f"| {mission['instruction']} | {expected} |"
        )

    lines += ["", "#### Multi-drone", ""]
    for mission in multi:
        lines += [
            f"**{mission['id']}** — {mission.get('category', '')} "
            f"({mission['drones']} drones)",
            "",
            "| Drone | Instruction | Expected sequence |",
            "|---|---|---|",
        ]
        expectations = mission.get("expected_per_drone", [])
        for index, instruction in enumerate(mission["instructions"]):
            expected = " → ".join(f"`{a}`" for a in expectations[index]) if index < len(expectations) else ""
            lines.append(f"| Drone{index + 1} | {instruction} | {expected} |")
        lines += ["", f"*{mission.get('note', '')}*", ""]

    lines += [
        "**Why each mission exists** is in `docs/BASELINE_MISSIONS.md`; **what has "
        "actually been run** is in `phases/phase-01-baseline-freeze/`.",
        "",
        END,
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--config", default=DEFAULT_CONFIG)
    parser.add_argument("--note", default=DEFAULT_NOTE)
    parser.add_argument("--check", action="store_true",
                        help="report whether the note is out of date; change nothing")
    args = parser.parse_args()

    if not os.path.isfile(args.note):
        sys.exit(f"note not found: {args.note}\n"
                 f"(pass --note if the vault moved)")

    block = render(load_toml(args.config))
    text = io.open(args.note, encoding="utf-8").read()

    if START in text and END in text:
        before = text[:text.index(START)]
        after = text[text.index(END) + len(END):]
        updated = before + block + after
    else:
        # First run: insert after section 1.3, before the exit criterion, which
        # is where a reader looking for the mission set will be.
        anchor = "\n## Exit criterion"
        if anchor not in text:
            sys.exit("cannot find '## Exit criterion' to insert before; "
                     "add the markers by hand and re-run")
        updated = text.replace(anchor, "\n" + block + "\n" + anchor, 1)

    if updated == text:
        print("note is up to date")
        return 0
    if args.check:
        print("NOTE IS OUT OF DATE -- re-run without --check")
        return 1

    io.open(args.note, "w", encoding="utf-8", newline="\n").write(updated)
    print(f"updated {os.path.basename(args.note)}")
    print(f"  {len(load_toml(args.config)['mission'])} missions written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
